# <center> Universidad de las Fuerzas Armadas</center>
  # <center> Métodos Numéricos</center>
   ## Actividad n.-2
   ## --------------------------------------------------------------------------------------------------------------------------------
   ### Apellidos: **Pallo Yautibug**
   ### Nombres: **Roberto Carlos**
   ### NRC:_3657_
   ## -------------------------------------------------------------------------------------------------------------------------------

## Ejercicios
 **1.-** Utilice todos los métodos estudiados (Newton, Bisección y Secante) para encontrar la raíz de la
siguiente función: $f(x) = x + cos x$ en el intervalo $[-2; 0]$, con cuatro cifras decimales.

## Método de Newton

Si tememos $f(x)=x+cos x$, entonces $f'(x)=1-sen x$

A continuación vamos a desarrollar las siguientes expresiones utlizando el algoritmo implementado para encontrar la raiz<br />
de las siguientes funciones por el Método de Newton.

In [462]:
import numpy as np
def newton(f,df,x0,nmax,tol):
    xi=x0
    for i in range(0,nmax):
        xi=xi-f(xi)/df(xi)
        if abs(f(xi)) < tol:
            print(xi,' encontrado con ',i,' iteraciones')
            break
    return None

In [463]:
f = lambda x: x+np.cos(x)# Funcion original
df = lambda x: 1-np.sin(x)# Encontramos la derivada de la función

In [464]:
newton(f,df,-2,20,1e-4)

-0.7390897242053693  encontrado con  1  iteraciones


## Método de Bisección

Si tememos $f(x)=x+cos x$, entonces: 

A continuación vamos a desarrollar las siguientes expresiones utlizando el algoritmo implementado para encontrar la raiz de <br />las siguientes funciones por el Método de bisección el cual consiste en tomar un intervalo $[a,b]$ e ir dividendo sucesivamente<br /> hasta hallar la raiz existente en el intervalo mas proximo.

In [465]:
import matplotlib.pyplot as plt
import numpy as np
#Definimos la funcion
def f(x):
    return x+np.cos(x)
  
#Definir la funcion para la biseccion 
def bisec(a,b,tol):
 
    if (f(a) * f(b) >= 0):
        print("No existe raiz en el rango ",a,",",b,"\n")
        return
    c = a
    i = 0
    n = 12
   
    while (abs(b-a) > tol):
        i=i+1
        #Se suma y divide para 2 los extremos del intervalo hast encontrar la raiz
        c = (a+b)/2
        # Comprobamos si el punto medio es la raíz 
        if (f(c) == 0.0):
            break
        # decidimos en cual intervalo continuamos con los pasos anteriores
        if (f(c)*f(a) < 0):
            b = c
        else:
            a = c         
    print("En la interración : ",i,"se encuentra aproximadamente la raiz en el intervalo",a,",",b)
       
    print("El valor de la raiz es : ",c)
    


In [466]:
# Inicializando Datos de intervalos y tolerancia
a = -2
b = 0
tol = 0.000001
bisec(a, b, tol)
 


En la interración :  21 se encuentra aproximadamente la raiz en el intervalo -0.7390851974487305 , -0.7390842437744141
El valor de la raiz es :  -0.7390851974487305


## Método de Secante

Si tememos $f(x)=x+cos x$, entonces:

Es un algoritmo o método de la secante parte de dos puntos ( no sólo uno como el método de Newton) y estima la tangente<br />
(es decir, la pendiente de la recta) por una aproximación.

In [467]:
import matplotlib.pyplot as plt
import numpy as np
#Definimos la funcion
def f(x):
    return x+np.cos(x)
#Definir la funcion para la secante  
def secante(a, b, tol):
    n = 0
    xm = 0
    x0 = 0
    c = 0
    if (f(a) * f(b) < 0):
        while True:
             
            # Calculamos el valor medio del intervalo
            x0 = ((a * f(b) - b * f(a)) /(f(b) - f(a)));
 
            # Comprobamos si x0 en la raiz buscada
            c = f(a) * f(x0);
 
            # Actualiza el valor de los intervalos
            a = b;
            b = x0;
 
            # Actualiza en uno el numero de interacciones
            n += 1;
 
            # Si x0 es raiz de la ecuación en el intervalo dado
            if (c == 0):
            # si x0 es la raiz detenemos el bucle
                break;
            xm = ((a * f(b) - b * f(a)) /(f(b) - f(a)));
             
            if(abs(xm - x0) < tol):
                break;
         
        print("Raiz de la función =",round(x0, 15));
        print("No. de interacciones= ", n);
         
    else:
        print("No posee raiz en el intervalo");



In [468]:
# Inicialización de datos como extremos del intervalo y tolerancia 
x1 = -2;
x2 = 0;
tol = 0.000001;
secante(x1, x2, tol);

Raiz de la función = -0.739085137019994
No. de interacciones=  5


**2.-** Encuentre la intersección de las siguientes funciones: $f(x) = 3 - x$ y $g(x) = ln x$, con tres cifras
decimales.

Sea: $f(x) = 3 - x$ y $g(x) = ln x$, entonces:



Igualamos a cero y formamos una nueva función:
$3 - x = lnx$<br />
$lnx - 3 + x = 0$<br />
$h(x) = lnx - 3 + x$<br />

Para encontrar el punto de intersección entre estas dos variables vamos a utilizar el Metodo de Newton:<br />
Utilizamos para esto los siguientes datos:<br />
$h(x) = lnx - 3 + x$<br />
$h'(x) = \frac{1}{x}+1$<br />
$Xn = x_a- \frac {ln - 3 + x} {h'(x)}$<br />
       

Vamos a comenzar con la segunda interacción; donde x_a=2<br />
$X_2=2-\frac {ln(2) - 3 + 2} {\frac{1}{2}+1}$<br />
$X_2=2-\frac {- 0,307 }{1,5}$<br />
$X_2=2-(-0,204)$<br />
$X_2=2,204)$<br />

Reemplazamos $X_2=2,204)$ en valor en $f(x) = 3 - x$:<br />
$f(x) = 3 - 2,204$:<br />
$f(x) = 0,796$:<br />

Respuesta:el punto de interseccion se encuentra en las coordenadas:<br />
        $X=2,204$<br />
        $Y = 0,796$:<br />

**3.-** Programe el método de sustitución regresiva. Analice el número de operaciones del algoritmo para
matrices de tamaño $3 x 3$.

In [7]:
import numpy as np

A = np.array([[1,6,5],[0,1,8],[0,0,1]])

B = np.array([[7],
              [9],
              [6]])

In [8]:
n=len(A) # numero de filas
x=np.zeros(n) # vector solucion
for i in range(ultfil,0-1,-1):
    pivote = AB[i,i]
    for k in range(i-1,0-1,-1):
        factor = AB[k,i]/pivote
        AB[k,:] = AB[k,:] - AB[i,:]*factor
    # diagonal a unos
    AB[i,:] = AB[i,:]/AB[i,i]
    x = np.copy(AB[:,ultcolum])

NameError: name 'ultfil' is not defined

In [9]:
print('Matriz aumentada:')
print(AB11)

Matriz aumentada:


NameError: name 'AB11' is not defined

In [10]:
print('solución de X: ')
print(x)

solución de X: 
[0. 0. 0.]


**4.-** Una importante parte de la física es la termodinámica que es el estudio de la transferencia de calor.
En este ejercicio vamos a determinar la distribución de temperatura de estado estable de una placa
delgada cuando se conoce la temperatura en los bordes.<br />
 Suponga que la placa que se ilustra en la figura representa una sección transversal de una viga de
metal, con flujo de calor despreciable en la dirección perpendicular a la placa. Sean T1, T2, T3 y
T4 las temperaturas en los cuatro nodos interiores de la malla en la figura. La temperatura en un
nodo es aproximadamente igual al promedio de las temperaturas de los cuatro nodos más cercanos,
esto es, a la izquierda, arriba, a la derecha y abajo.<br />
Escriba un sistema de ecuaciones cuya solución de estimaciones de las temperaturas T1, T2, T3 y
T4.

<img src='placa.png'>

La temperatura $T_1$ la puedo calcular como: $ 𝑻_𝟏=\frac{𝟏𝟎+𝟐𝟎+𝑻_𝟐+𝑻_3}{4}$<br /> Después  simplifico  las  constantes  y  reescribo  la  ecuación  obteniendo $𝟒𝑻_𝟏−𝑻_𝟐−𝑻_3+ 0T_4 = 𝟑𝟎$, ésta  expresión  me  representa  la  primera  ecuación  de  mi  sistema  de ecuaciones lineales.

La temperatura $T_2$ la puedo calcular como: $ 𝑻_2=\frac{𝑻_1+20+40+𝑻_4}{4}$<br /> 
Después  simplifico  las  constantes  y  reescribo  la  ecuación  obteniendo $−𝑻_1+𝟒𝑻_2+0T_3−𝑻_4 = 6𝟎$, ésta  expresión  me  representa  la  primera  ecuación  de  mi  sistema  de ecuaciones lineales.

La temperatura $T_3$ la puedo calcular como: $ 𝑻_3=\frac{10+𝑻_1+𝑻_4+30}{4}$<br /> 
Después  simplifico  las  constantes  y  reescribo  la  ecuación  obteniendo $−𝑻_1+ 0T_2+𝟒𝑻_3-T_4 = 4𝟎$, ésta  expresión  me  representa  la  primera  ecuación  de  mi  sistema  de ecuaciones lineales.

La temperatura $T_4$ la puedo calcular como: $ 𝑻_4=\frac{𝑻_3+𝑻_2+40+30}{4}$<br /> 
Después  simplifico  las  constantes  y  reescribo  la  ecuación  obteniendo $0𝑻_1−𝑻_2-T_3+𝟒𝑻_4 = 70$, ésta  expresión  me  representa  la  primera  ecuación  de  mi  sistema  de ecuaciones lineales.

Tenemos entonces el siguiente sistema de ecuaciones:
   $$
f(x)=\left\{
\begin{array}{ll}
𝟒𝑻_𝟏−𝑻_𝟐−𝑻_3+ 0T_4 = 𝟑𝟎 &  \\
−𝑻_1+𝟒𝑻_2+0T_3−𝑻_4 = 6𝟎  &  \\
−𝑻_1+ 0T_2+𝟒𝑻_3-T_4 = 4𝟎  &  \\
0𝑻_1−𝑻_2-T_3+𝟒𝑻_4 = 70  &  \\
\end{array}
\right.
$$

Programe el método de eliminación gaussiana y halle el valor de estas temperaturas. Utilice como
apoyo el ejercicio del literal anterior.

In [14]:
import numpy as np
A = np.array([[4,-1,-1, 0],[-1,4,0,-1],[-1,0,4,-1],[0,-1,-1,4]])

B= np.array([[30],
              [60],
              [40],
              [70]])


In [15]:
# Matriz aumentada
AB  = np.concatenate((A,B),axis=1)
AB0 = np.copy(AB)

In [18]:
# elimina hacia atras
ultfil = n-1
ultcolum = m-1
for i in range(ultfil,0-1,-1):
    pivot = AB[i,i]
    for k in range(i-1,0-1,-1):
        factor = AB[k,i]/pivot
        AB[k,:] = AB[k,:] - AB[i,:]*factor
    # diagonal a unos
    AB[i,:] = AB[i,:]/AB[i,i]
a = np.copy(AB[:,ultcolum])
a = np.transpose([a])


NameError: name 'm' is not defined

In [17]:
print('solución de X: ')
print(a)

solución de X: 


NameError: name 'a' is not defined

**5.-** Programe el pivoteo parcial en el algoritmo de eliminación gaussiana. Utilice este nuevo programa
para resolver el ejercicio anterior. Compare los resultados.

In [19]:
import numpy as np

# INGRESO
A = np.array([[4,-1,-1, 0],[-1,4,0,-1],[-1,0,4,-1],[0,-1,-1,4]])

B = np.array([[30],
              [60],
              [40],
              [70]])

In [20]:

# Evitar truncamiento en operaciones
A = np.array(A,dtype=float) 
# Matriz aumentada
AB = np.concatenate((A,B),axis=1)
AB1 = np.copy(AB)

In [21]:
# Pivoteo parcial por filas
tam = np.shape(AB)
n = tam[0]
m = tam[1]

In [22]:
# Para cada fila en AB
for i in range(0,n-1,1):
    # columna desde diagonal i en adelante
    columna = abs(AB[i:,i])
    dife = np.argmax(columna)

    # buscar 0 está en diagonal
    if (dife !=0):
        # intercambia filas
        temporal = np.copy(AB[i,:])
        AB[i,:] = AB[dife+i,:]
        AB[dife+i,:] = temporal
        AB2 = np.copy(AB)   

In [23]:
# eliminacion hacia adelante
for i in range(0,n-1,1):
    pivote = AB[i,i]
    adelante = i + 1
    for k in range(adelante,n,1):
        factor = AB[k,i]/pivote
        AB[k,:] = AB[k,:] - AB[i,:]*factor
        AB2 = np.copy(AB)

In [24]:
# elimina hacia atras
ultfila = n-1
ultcolumna = m-1
for i in range(ultfila,0-1,-1):
    pivot = AB[i,i]
    atras = i-1 
    for k in range(atras,0-1,-1):
        factor = AB[k,i]/pivot
        AB[k,:] = AB[k,:] - AB[i,:]*factor
    # diagonal a unos
    AB[i,:] = AB[i,:]/AB[i,i]
X = np.copy(AB[:,ultcolumna])
X = np.transpose([X])

In [25]:
print('Matriz aumentada:')
print(AB1)

Matriz aumentada:
[[ 4. -1. -1.  0. 30.]
 [-1.  4.  0. -1. 60.]
 [-1.  0.  4. -1. 40.]
 [ 0. -1. -1.  4. 70.]]


In [26]:
print("Pivoteo Parcial")
print(AB2)

Pivoteo Parcial
[[  4.          -1.          -1.           0.          30.        ]
 [  0.           3.75        -0.25        -1.          67.5       ]
 [  0.           0.           3.73333333  -1.06666667  52.        ]
 [  0.           0.           0.           3.42857143 102.85714286]]


In [27]:
print('eliminacion hacia adelante')
print(AB2)

eliminacion hacia adelante
[[  4.          -1.          -1.           0.          30.        ]
 [  0.           3.75        -0.25        -1.          67.5       ]
 [  0.           0.           3.73333333  -1.06666667  52.        ]
 [  0.           0.           0.           3.42857143 102.85714286]]


In [28]:
print('eliminación hacia atrás')
print(AB)

eliminación hacia atrás
[[ 1.   0.   0.   0.  20. ]
 [ 0.   1.   0.   0.  27.5]
 [ 0.   0.   1.   0.  22.5]
 [ 0.   0.   0.   1.  30. ]]


In [29]:
print('solución de X: ')
print(X)

solución de X: 
[[20. ]
 [27.5]
 [22.5]
 [30. ]]


Respuesta:Difieren muchos los resultados:

In [509]:
print('solución de Metodo Eliminación Gauss: ')
print(a)
print('solución de Metodo con Pivoteo Parcial o Gauss-Jordan: ')
print(X)

solución de Metodo Eliminación Gauss: 
[[37]
 [25]
 [19]
 [17]]
solución de Metodo con Pivoteo Parcial o Gauss-Jordan: 
[[20. ]
 [27.5]
 [22.5]
 [30. ]]


Por conclusión El metodo del pivoteo parcial es mas preciso.